on:
  push:
    branches:
      - main

name: Release new version

env:
  AWS_DEFAULT_REGION: eu-west-2

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Read .nvmrc for node version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node (${{ steps.nvm.outputs.NODE_VERSION }})
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: NPM Install
        run: npm ci

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
